export const types = {
    //login
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",

    AUTH_LOADING: "AUTH_LOADING",
    AUTH_ERROR: "AUTH_ERROR",

    GET_SESSION_TOKEN_SUCCESS: "GET_SESSION_TOKEN_SUCCESS",
    GET_SESSION_TOKEN_FAILURE: "GET_SESSION_TOKEN_FAILURE",

    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    CLEAR_USER_DETAILS: "CLEAR_USER_DETAILS",

    FETCH_ORDERS : 'FETCH_ORDERS',
    FETCH_ORDERS_SUCCESS : 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILURE : 'FETCH_ORDERS_FAILURE',

    FILTER_ORDER : 'FILTER_ORDER',

    //update order
    CHANGE_EVENT_TYPE: 'CHANGE_EVENT_TYPE',
	CHANGE_EVENT_TYPE_SUCCESS: 'CHANGE_EVENT_TYPE_SUCCESS',
	CHANGE_EVENT_TYPE_FAILURE: 'CHANGE_EVENT_TYPE_FAILURE',
	CHANGE_EVENT_TYPE_MODAL_CLOSE: 'CHANGE_EVENT_TYPE_MODAL_CLOSE',

    FETCH_LIST: 'FETCH_LIST',
    FETCH_LIST_SUCCESS : 'FETCH_LIST_SUCCESS',
    FETCH_LIST_FAILURE : 'FETCH_LIST_FAILURE',

    SESSION_EXPIRED: 'SESSION_EXPIRED',
    SESSION_MODAL_CLOSE: 'SESSION_MODAL_CLOSE',
}  